### ISSUE TITLE
你好，功能可以开放给第三软件调用吗？

### ISSUE THREAD

**Issue by 157276303** [johnson0612/WeChat-Plus#6]

**Comment by johnson0612** [comment]
原则上可以，你需要什么功能接口呢，可以加@jason770612

**Comment by 157276303** [comment]
微信吗？

**Comment by 157276303** [comment]
怎么联系你呢？

**Comment by 157276303** [comment]
> 原则上可以，你需要什么功能接口呢，可以加@jason770612

搜索不到，这个是什么联系方式？我只要各类消息的接收和个人信息查询，和发文本消息就可以了

**Comment by johnson0612** [comment]
> 

Telegram

**Comment by johnson0612** [comment]
> 微信吗？

Telegram

**Comment by johnson0612** [comment]
> > 原则上可以，你需要什么功能接口呢，可以加@jason770612
> 
> 搜索不到，这个是什么联系方式？我只要各类消息的接收和个人信息查询，和发文本消息就可以了

可以提供接口

**Comment by 157276303** [comment]
没有这个，网格也支持。有点麻烦。需要付多钱呢，有没有试用。我们先简单沟通一下，可以吗！后面我会把这记录删除！

**Comment by 157276303** [comment]
网格也支持=网络也不支持

**Comment by 157276303** [comment]
可以提供一个邮箱联系吗？

**Comment by johnson0612** [comment]
> 可以提供一个邮箱联系吗？

你留个邮箱，我发你

**Comment by 157276303** [comment]
eqycum@mailto.plus

**Comment by 157276303** [comment]
谢谢 ！

**Comment by johnson0612** [comment]
> [eqycum@mailto.plus](mailto:eqycum@mailto.plus)

已发

**Comment by 157276303** [comment]
你好，我已经用自己邮箱联系你了。请回复，谢谢！
