### ISSUE TITLE
有提供api文档吗

### ISSUE THREAD

**Issue by chuilishi** [johnson0612/WeChat-Plus#7]
想用python实现一些自动化

**Comment by johnson0612** [comment]
请看C++接口头文件注释

**Comment by xqsoft** [comment]
c++ 头文件注释仅适用c++  想用python写的话  也不知道怎么个顺序调用  建议提供个例子

**Comment by johnson0612** [comment]
> c++ 头文件注释仅适用c++ 想用python写的话 也不知道怎么个顺序调用 建议提供个例子

目前只提供C++接口，最近没时间去支持python

**Comment by Carlkin** [comment]
用着用着就收费了
